Controllers/Api/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Identity;
using TwitterClone.Database;
using TwitterClone.ViewModels;
using System.Security.Claims;
using AutoMapper;
using Microsoft.Extensions.Logging;
using System.Net;
using TwitterClone.Models;
using Microsoft.AspNet.Authorization;
using SendGridMessenger;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TwitterClone.Controllers.Api
{
    [Route("api/user")]
    public class UserController : Controller
    {
        private SignInManager<TwitterCloneUser> m_signInManager;
        private UserManager<TwitterCloneUser> m_userManager;
        private ILogger<UserController> m_logger;
        private IEmailSender m_emailSender;

        public UserController(SignInManager<TwitterCloneUser> a_signInManager, UserManager<TwitterCloneUser> a_userManager, ILogger<UserController> a_logger, IEmailSender a_emailSender)
        {
            m_signInManager = a_signInManager;
            m_userManager = a_userManager;
            m_logger = a_logger;
            m_emailSender = a_emailSender;
        }

        [Route("{userName}")]
        public async Task<JsonResult> Get(string userName)
        {
            var user = await m_userManager.FindByNameAsync(userName);
            var results = Mapper.Map<TwitterCloneUserViewModel>(await m_userManager.FindByIdAsync(user.Id));
            return Json(results);
        }

        [HttpPost]
        public async Task<JsonResult> Post([FromBody]SignupViewModel vm, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { error = "Unknown sign up error." });
            }

            if (vm.Password != vm.ConfirmPassword)
            {
                return Json(new { error = "The passwords you entered did not match." });
            }

            var userFound = await m_userManager.FindByNameAsync(vm.Username);
            if (userFound != null)
            {
                return Json(new { error = "This username is already in use." });
            }

            userFound = await m_userManager.FindByEmailAsync(vm.Email);
            if (userFound != null)
            {
                return Json(new { error = "This email address is already in use." });
            }

            var newUser = new TwitterCloneUser()
            {
                UserName = vm.Username,
                Email = vm.Email
            };

            var signUpResult = await m_userManager.CreateAsync(newUser, vm.Password);
            if (!signUpResult.Succeeded)
            {
                if (signUpResult.Errors.Any())
                {
                    if (signUpResult.Errors.First().Code == "InvalidUserName")
                    {
                        return Json(new { error = "Invalid username. Usernames can only contain letters, numbers, and .-_" });
                    }
                }
                return Json(new { error = "Unknown sign up error." });
            }

            await SendConfirmationEmail(newUser);

            return Json(new { url = "confirmemailsent" });
        }

        [HttpPost ("ResendConfirmationEmail")]
        public async Task<IActionResult> ResendConfirmationEmail()
        {
            var user = await m_userManager.FindByIdAsync(User.GetUserId());
            await SendConfirmationEmail(user);
            return RedirectToAction("ConfirmEmailSent", "Auth");
        }

        public async Task SendConfirmationEmail(TwitterCloneUser a_user)
        {
            var code = await m_userManager.GenerateEmailConfirmationTokenAsync(a_user);
            var callbackUrl = Url.Action("EmailConfirmed", "Auth", new { userId = a_user.Id, code = code }, protocol: HttpContext.Request.Scheme);
            var emailBody = $"Please confirm your account by clicking this link: <br/> <a href=\"{callbackUrl}\"> {callbackUrl} </a>";
            await m_emailSender.SendEmailAsync(a_user.Email, "Confirm your account", emailBody);
        }

        [HttpPost("ChangePassword")]
        public async Task<JsonResult> ChangePassword([FromBody]ChangePasswordViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { error = "Please fill out all fields." });
            }

            if (vm.NewPassword != vm.ConfirmPassword)
            {
                return Json(new { error = "Passwords do not match." });
            }

            var user = await m_userManager.FindByIdAsync(User.GetUserId());
            if (user != null)
            {
                var result = await m_userManager.ChangePasswordAsync(user, vm.CurrentPassword, vm.NewPassword);
                if (result.Succeeded)
                {
                    await m_signInManager.SignInAsync(user, isPersistent: false);
                    m_logger.LogInformation(3, "User changed their password successfully.");
                    return Json(new { url = "myaccount?actionTaken=PasswordChanged" });
                }
                return Json(new { error = "Current Password is incorrect." });
            }
            return Json(new { error = "Unknown Error." });
        }

        //
        // POST: /Account/ResetPassword
        [HttpPost("ResetPassword")]
        [AllowAnonymous]
        public async Task<JsonResult> ResetPassword([FromBody]ResetPasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { url = "/" });
            }
            var user = await m_userManager.FindByEmailAsync(model.Email);
            if (user == null)
            {
                // Don't reveal that the user does not exist
                return Json(new { url = "/" });
            }

            //ASP.NET is failing to decode a "+" in a URL. Need to manually decode it.
            string decodedCode = model.Code.Replace(@"&#x2B;", "+");

            var result = await m_userManager.ResetPasswordAsync(user, decodedCode, model.Password);
            if (result.Succeeded)
            {
                return Json(new { url = "/PasswordReset" });
            }
            return Json(new { url = "/PasswordReset" });
        }
    }
}

Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Identity;
using TwitterClone.Database;
using TwitterClone.ViewModels;
using System.Security.Claims;
using AutoMapper;
using Microsoft.Extensions.Logging;
using System.Net;
using TwitterClone.Models;
using Microsoft.AspNet.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TwitterClone.Controllers
{
    public class SessionController : Controller
    {
        private SignInManager<TwitterCloneUser> m_signInManager;
        private UserManager<TwitterCloneUser> m_userManager;
        private ILogger<SessionController> m_logger;

        public SessionController(SignInManager<TwitterCloneUser> a_signInManager, UserManager<TwitterCloneUser> a_userManager, ILogger<SessionController> a_logger)
        {
            m_signInManager = a_signInManager;
            m_userManager = a_userManager;
            m_logger = a_logger;
        }

        [HttpGet]
        public async Task<JsonResult> CurrentUser()
        {
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    var user = await m_userManager.FindByIdAsync(User.GetUserId());
                    return Json(Mapper.Map<TwitterCloneUserViewModel>(user));
                }

                Response.StatusCode = (int)HttpStatusCode.Forbidden;
                return Json(new { Message = "You are not logged in" });
            }
            catch (Exception ex)
            {
                m_logger.LogError("Failed to get current user", ex);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { Message = ex.Message });
            }
        }

        [HttpPost]
        public async Task<JsonResult> Login([FromBody]LoginViewModel vm, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { error = "Sign in Error" });
            }

            string username;
            if (vm.Username.Contains("@"))
            {
                var userFound = await m_userManager.FindByEmailAsync(vm.Username);
                if (userFound == null)
                {
                    return Json(new { error = "Username or password incorrect" });
                }
                username = userFound.UserName;
            }
            else
            {
                username = vm.Username;
            }

            var signInResult = await m_signInManager.PasswordSignInAsync(username, vm.Password, true, false);
            if (!signInResult.Succeeded)
            {
                return Json(new { error = "Username or password incorrect" });
            }

            if (!String.IsNullOrWhiteSpace(returnUrl))
            {
                return Json(new { url = returnUrl });
            }

            return Json(new { url = "" });
        }

        [HttpPost]
        public async Task<IActionResult> Signout()
        {
            if (User.Identity.IsAuthenticated)
            {
                await m_signInManager.SignOutAsync();
            }

            Response.StatusCode = (int)HttpStatusCode.SeeOther;

            return RedirectToAction("Index", "App");
        }
    }
}

Views/App/About.cshtml
@{
    ViewBag.Title = "About";
}

    <h1>About</h1>

Views/App/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<h1>Contact</h1>

Views/App/Index.cshtml
@{
    ViewBag.Title = "Main Page";
}

@section Scripts {
    <script src="~/lib/signalr/jquery.signalR.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/js/controllers/TwitterClonesController.js"></script>
    <script src="~/js/TwitterCloneSignalR.js"></script>
}

<div ng-controller="TwitterClonesController as vm">
    <div class="alert alert-danger" role="alert" ng-show="vm.errorMessage" ng-cloak>
        <i class="fa fa-exclamation-triangle"></i>
        <span ng-bind="vm.errorMessage"></span>
    </div>
    <div id="TwitterClone-form" class="container-fluid">
        <form novalidate name="newTwitterClonePostForm" ng-Submit="vm.addTwitterClonePost()">
            <h4> @@@User.Identity.Name says </h4>
            <div class="form-group">
                <textarea id="TwitterClonePostText" class="form-control" ng-minlength="5" ng-maxlength="255" rows="3" placeholder="Say something"
                            ng-model="vm.newTwitterClonePost.message" required></textarea>
            </div>
            <button type="submit" ng-disabled="newTwitterClonePostForm.$invalid" class="btn submit-btn pull-right">TwitterClone!</button>
        </form>
    </div>

    <div ng-show="vm.firstLoad" id="post-stream" class="container-fluid" ng-cloak>
        <div class="post" ng-repeat="TwitterClonePost in vm.TwitterClonePosts | orderBy:'created_at':true" ng-class-odd="'odd'" ng-class-even="'even'">
            <TwitterClone-post-item TwitterClone-post="TwitterClonePost"></TwitterClone-post-item>
        </div>
    </div>
</div>

Views/App/MyAccount.cshtml
@model TwitterClone.PageModels.AccountSettingsPageModel
@{
    ViewBag.Title = "Account Settings";
}

<div class="row">
    <div class="col-md-12">
        <h1>Account Settings - @Model.UserVM.UserName</h1>
        @if (!String.IsNullOrWhiteSpace(Model.SuccessMessage))
        {
            <div class="alert alert-success" role="alert">@Model.SuccessMessage</div>
        }
        <br/>
        <table class="table">
            <tr>
                <td>
                    Email
                </td>
                <td>
                    @Model.UserVM.Email
                </td>

                @if (Model.UserVM.EmailConfirmed)
                {
                    <td>
                        Confirmed
                    </td>
                }
                else
                {
                    <td>
                        <span>Unconfirmed</span>
                        <form class="resend-email" action="api/user/ResendConfirmationEmail" method="post">
                            <button type="submit" class="btn btn-sm btn-info">Resend Confirmation Email</button>
                        </form>
                    </td>
                }

            </tr>
            <tr>
                <td>
                    Password
                </td>
                <td>
                    ***************
                </td>
                <td>
                    <a asp-controller="Auth" asp-action="ChangePassword">Change Password</a>
                </td>
            </tr>
            <tr>
                <td>
                    Profile Picture
                </td>
                <td>
                    <img src="image/profilepicture/@User.Identity.Name" class="profilepicture" alt="Profile Picture" />
                </td>
                <td>
                    <a asp-controller="Auth" asp-action="ChangeProfilePicture">Change Profile Picture</a>
                </td>
            </tr>
        </table>
    </div>
</div>

Views/App/Signout.cshtml
@model TwitterClone.ViewModels.LoginViewModel
@{
    ViewBag.Title = "Signout";
}

<div>
    <h1>Signout</h1>
    <div class="col-md-6 col-md-offset-3">
        <h3>Click below to sign out of TwitterClone:</h3>
        <form asp-controller="Session" asp-action="Signout" method="post">
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg">Signout</button>
            </div>
        </form>
    </div>
</div>

Views/App/User.cshtml
@model TwitterClone.ViewModels.TwitterCloneUserViewModel
@{
    ViewBag.Title = $"{Model.UserName} - User Page";
}

@section Scripts {
    <script src="~/lib/signalr/jquery.signalR.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/js/controllers/userController.js"></script>
    <script src="~/js/TwitterCloneSignalR.js"></script>
}

<div ng-controller="userController as vm" ng-init="vm.init('@Model.UserName')">
    <div ng-show="vm.pageReady">
        <h1 ng-bind-template="User: {{vm.user.userName}}"></h1>
        <h5 ng-bind-template="Email: {{vm.user.email}}"></h5>
    </div>
    <div ng-show="vm.pageReady" ng-cloak>
        <h3>TwitterClones</h3>
        <div id="post-stream" class="container-fluid" ng-show="vm.hasTwitterClones()">
            <div class="post" ng-repeat="TwitterClonePost in vm.TwitterClonePosts | orderBy:'created_at':true" ng-class-odd="'odd'" ng-class-even="'even'">
                <TwitterClone-post-item TwitterClone-post="TwitterClonePost"></TwitterClone-post-item>
            </div>
        </div>
        <div ng-hide="vm.hasTwitterClones()">
            <div class="alert alert-info" role="alert">
                <i class="fa fa-exclamation-triangle"></i>
                <span>This user has no TwitterClones.</span>
            </div>
        </div>
    </div>
</div>

        